version: '3'
services:
  frontend:
    restart: always
    build: frontend
    ports:
    - "80:80"
  mongodb:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - "27017:27017"
    volumes:
    - 'mongo:/data/db'
volumes:
  mongo: